import { NextResponse } from 'next/server';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

// Extend jsPDF type to include autoTable
declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: any) => jsPDF;
    lastAutoTable: {
      finalY: number;
    };
  }
}

export async function POST(request: Request) {
  try {
    const { appMeta, rollupContent, analysisMetrics, affiliateCode, userEmail } = await request.json();
    
    const doc = new jsPDF('p', 'mm', 'a4');
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    let yPosition = 20;
    
    // Helper function to add new page if needed
    const checkPageBreak = (neededSpace: number = 20) => {
      if (yPosition + neededSpace > pageHeight - 20) {
        doc.addPage();
        yPosition = 20;
        return true;
      }
      return false;
    };
    
    // Helper to add footer on each page
    const addFooter = (pageNum: number, totalPages: number) => {
      const footerY = pageHeight - 10;
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text('Generated by App Ideas Finder | www.appideasfinder.com', pageWidth / 2, footerY, { align: 'center' });
      doc.text(`Page ${pageNum} of ${totalPages}`, pageWidth - 20, footerY, { align: 'right' });
    };
    
    // === COVER PAGE ===
    // Header with logo area
    doc.setFillColor(136, 209, 138); // #88D18A
    doc.rect(0, 0, pageWidth, 40, 'F');
    
    doc.setFontSize(28);
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.text('APP IDEAS FINDER', pageWidth / 2, 25, { align: 'center' });
    
    // App Name and Info
    yPosition = 60;
    doc.setFontSize(24);
    doc.setTextColor(40, 40, 40);
    doc.setFont('helvetica', 'bold');
    doc.text(`Analysis Report: ${appMeta?.trackName || 'Unknown App'}`, 20, yPosition, { maxWidth: pageWidth - 40 });
    
    yPosition += 15;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 100);
    doc.text(`Developer: ${appMeta?.artistName || 'Unknown'}`, 20, yPosition);
    
    yPosition += 8;
    doc.text(`Rating: ${appMeta?.averageUserRating?.toFixed(1) || 'N/A'} ★ (${appMeta?.userRatingCount?.toLocaleString() || 0} ratings)`, 20, yPosition);
    
    yPosition += 8;
    doc.text(`Analysis Date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, 20, yPosition);
    
    yPosition += 8;
    doc.text(`Reviews Analyzed: ${analysisMetrics?.reviewCount?.toLocaleString() || 0}`, 20, yPosition);
    
    // Summary Box
    yPosition += 20;
    doc.setFillColor(240, 250, 245);
    doc.roundedRect(20, yPosition, pageWidth - 40, 35, 3, 3, 'F');
    
    yPosition += 8;
    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);
    doc.setFont('helvetica', 'italic');
    const summaryText = 'This comprehensive 12-section analysis provides actionable insights for building a successful app based on real user feedback from the App Store.';
    const splitSummary = doc.splitTextToSize(summaryText, pageWidth - 50);
    doc.text(splitSummary, 25, yPosition);
    
    // === SECTIONS START ===
    doc.addPage();
    yPosition = 20;
    
    const sections = [
      { key: 'likes', title: '1. What People Like About the App', icon: '👍' },
      { key: 'dislikes', title: "2. What Users Want (and Don't Want)", icon: '💭' },
      { key: 'recommendations', title: '3. Top Recommendations', icon: '⭐' },
      { key: 'keywords', title: '4. Suggested Keywords', icon: '🔍' },
      { key: 'definitely', title: '5. Core Features to Include', icon: '🎯' },
      { key: 'backlog', title: '6. Additional Features', icon: '✨' },
      { key: 'description', title: '7. Suggested App Description', icon: '📝' },
      { key: 'names', title: '8. Suggested App Names', icon: '💡' },
      { key: 'prp', title: '9. Product Requirements Prompt', icon: '📋' },
      { key: 'similar', title: '10. Similar Apps', icon: '📱' },
      { key: 'pricing', title: '11. Suggested Pricing Model', icon: '💰' },
    ];
    
    sections.forEach((section, index) => {
      const content = rollupContent[section.key];
      if (!content || content.length === 0) return;
      
      checkPageBreak(30);
      
      // Section Header
      doc.setFillColor(136, 209, 138);
      doc.roundedRect(20, yPosition, pageWidth - 40, 12, 2, 2, 'F');
      
      doc.setFontSize(14);
      doc.setTextColor(255, 255, 255);
      doc.setFont('helvetica', 'bold');
      doc.text(`${section.icon} ${section.title}`, 25, yPosition + 8);
      
      yPosition += 18;
      
      // Section Content
      doc.setFontSize(10);
      doc.setTextColor(60, 60, 60);
      doc.setFont('helvetica', 'normal');
      
      if (section.key === 'keywords' || section.key === 'names') {
        // Display as tags
        const tags = Array.isArray(content) ? content : [];
        const tagText = tags.join(', ');
        const splitText = doc.splitTextToSize(tagText, pageWidth - 50);
        doc.text(splitText, 25, yPosition);
        yPosition += splitText.length * 5 + 10;
        
      } else if (section.key === 'backlog') {
        // Display with priorities
        const items = Array.isArray(content) ? content : [];
        items.forEach((item: any) => {
          checkPageBreak(15);
          const priority = item.priority || 'Low';
          const color: [number, number, number] = priority === 'High' ? [220, 53, 69] : priority === 'Medium' ? [255, 193, 7] : [40, 167, 69];
          
          doc.setTextColor(color[0], color[1], color[2]);
          doc.setFont('helvetica', 'bold');
          doc.text(`• ${priority} Priority:`, 25, yPosition);
          
          doc.setTextColor(60, 60, 60);
          doc.setFont('helvetica', 'normal');
          const contentText = doc.splitTextToSize(item.content, pageWidth - 55);
          doc.text(contentText, 30, yPosition + 5);
          yPosition += contentText.length * 5 + 8;
        });
        
      } else if (section.key === 'similar') {
        // Display similar apps
        const apps = Array.isArray(content) ? content : [];
        apps.slice(0, 6).forEach((app: any) => {
          checkPageBreak(20);
          doc.setFont('helvetica', 'bold');
          doc.text(`• ${app.trackName || 'Unknown'}`, 25, yPosition);
          
          doc.setFont('helvetica', 'normal');
          yPosition += 5;
          doc.text(`  ${app.artistName || 'Unknown Developer'}`, 27, yPosition);
          yPosition += 5;
          doc.text(`  ★ ${app.averageUserRating?.toFixed(1) || 'N/A'} (${app.userRatingCount?.toLocaleString() || 0} ratings)`, 27, yPosition);
          yPosition += 8;
        });
        
      } else if (section.key === 'prp' || section.key === 'pricing' || section.key === 'description') {
        // Long form content
        const text = Array.isArray(content) ? content[0] : content;
        if (text) {
          // Remove markdown and HTML
          const cleanText = text.replace(/<[^>]*>/g, '').replace(/\*\*(.*?)\*\*/g, '$1').replace(/---/g, '');
          const splitText = doc.splitTextToSize(cleanText, pageWidth - 50);
          
          splitText.forEach((line: string) => {
            checkPageBreak(10);
            doc.text(line, 25, yPosition);
            yPosition += 5;
          });
          yPosition += 5;
        }
        
      } else {
        // Regular bullet lists
        const items = Array.isArray(content) ? content : [];
        items.forEach((item: string) => {
          checkPageBreak(15);
          // Remove markdown bold
          const cleanItem = item.replace(/\*\*(.*?)\*\*/g, '$1');
          const splitItem = doc.splitTextToSize(`• ${cleanItem}`, pageWidth - 55);
          doc.text(splitItem, 25, yPosition);
          yPosition += splitItem.length * 5 + 3;
        });
      }
      
      yPosition += 10;
    });
    
    // === TIME & COST SAVINGS (Section 12) ===
    doc.addPage();
    yPosition = 20;
    
    doc.setFillColor(136, 209, 138);
    doc.roundedRect(20, yPosition, pageWidth - 40, 12, 2, 2, 'F');
    doc.setFontSize(14);
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.text('⏱️ 12. Time & Cost Savings Analysis', 25, yPosition + 8);
    
    yPosition += 20;
    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);
    doc.setFont('helvetica', 'normal');
    doc.text(`AI Analysis completed in seconds, saving significant time and cost compared to manual analysis.`, 25, yPosition);
    
    // === AFFILIATE SECTION ===
    doc.addPage();
    yPosition = 20;
    
    // Header
    doc.setFillColor(255, 138, 26); // Orange
    doc.roundedRect(20, yPosition, pageWidth - 40, 25, 3, 3, 'F');
    
    yPosition += 8;
    doc.setFontSize(16);
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.text('💰 Earn With App Ideas Finder', 25, yPosition);
    
    yPosition += 7;
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text('Join our affiliate program and earn 25% commission', 25, yPosition);
    
    yPosition += 20;
    
    // Affiliate Details Box
    doc.setFillColor(250, 250, 250);
    doc.roundedRect(20, yPosition, pageWidth - 40, 50, 3, 3, 'F');
    
    yPosition += 10;
    doc.setFontSize(12);
    doc.setTextColor(40, 40, 40);
    doc.setFont('helvetica', 'bold');
    doc.text('Your Exclusive Affiliate Details:', 25, yPosition);
    
    yPosition += 10;
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(60, 60, 60);
    doc.text(`Affiliate Code: ${affiliateCode}`, 25, yPosition);
    
    yPosition += 8;
    doc.text(`Affiliate URL: www.appideasfinder.com?ref=${affiliateCode}`, 25, yPosition);
    
    yPosition += 15;
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    const affiliateText = 'Share this link and earn commissions: $9.75-$199.75 per referral! Visit www.appideasfinder.com/affiliate for full details.';
    const splitAffiliate = doc.splitTextToSize(affiliateText, pageWidth - 50);
    doc.text(splitAffiliate, 25, yPosition);
    
    // Add footer to all pages
    const totalPages = doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      addFooter(i, totalPages);
    }
    
    // Generate PDF as buffer
    const pdfBuffer = Buffer.from(doc.output('arraybuffer'));
    
    return new NextResponse(pdfBuffer, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="app-analysis-${appMeta?.trackName || 'report'}.pdf"`,
      },
    });
    
  } catch (error) {
    console.error('PDF generation error:', error);
    return NextResponse.json({ error: 'Failed to generate PDF' }, { status: 500 });
  }
}

